POST http://localhost:5500/ HTTP/1.1
Content-Type: application/json

{
  "nickname": "Thor Odinson",
  "realName": "Chris Hemsworth",
  "originDescription": "Thor is a very tall and well-built Asgardian male; he has very large biceps and long, muscular legs. Fair-skinned and blue-eyed, he has golden blond hair that grows slightly.",
  "superpower": "superhuman strength",
  "catchPhrase": "Our ancestors called it magic, and you called it science. I come from a country where both are the same.",
  "gender": "male",
  "birthday": "1962-08-01"
}